
pipeline {
  environment {
    registry = "bbhupati/demo"
    registryCredential = 'docker-hud-id'
    dockerImage = ''
  }
    agent any
    stages{
         stage('download_modules'){
             steps {
                dir ('modules') {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/master']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'mp_task']],
                        submoduleCfg: [],
                        userRemoteConfigs: [[
                            credentialsId: '',
                            url: 'https://github.com/nithura/mp_task.git'
                        ]]
                    ])
                }
            }
        }
    stage('Building image') {
      steps{
        dir ('modules/mp_task/docker') {
            script {
                dockerImage = docker.build registry + ":$BUILD_NUMBER" 
           }
        }
      }
    }
    stage('push image to docker-hub') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
              dockerImage.push()

          }
        }
      }
    }
    stage('pull image from docker-hub') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
              docker.image("bbhupati/demo:$BUILD_NUMBER").pull()

          }
        }
      }
    }
    stage('Docker deploy nodejs app'){
      steps{
          sh 'docker run -d --restart always --name nodejs-${BUILD_NUMBER} -p 80:3000 bbhupati/demo:${BUILD_NUMBER}'
        }
    }
    stage('Remove Unused docker-image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
  }
}
